#!/bin/bash
set -e
cd /tmp/

MYSQL_HOST=$MYSQL_HOST
MYSQL_PORT=${MYSQL_PORT:-3306}
MYSQL_USER=$MYSQL_USER
MYSQL_PASSWD=$MYSQL_PASSWD
MYSQL_DB=$MYSQL_DB
SQL_FILES=$SQL_FILES
COMMAND=$(which mysql || which mariadb)

function log() {
    echo "$@"
}

# check mysql connection
function check_conn() {
    $COMMAND -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWD -P$MYSQL_PORT $MYSQL_DB -e "select 1;" > /dev/null
    return $?
}

# exec sql files
function exec_sql_file() {
    until [ -z "$1" ]; do
        if echo $1 |egrep 'http[s]{0,1}://' >/dev/null 2>&1; then
            sql_file=$(basename $1)
            curl $1 -o $sql_file
        else
            sql_file=$1
        fi
        
        $COMMAND -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWD -P$MYSQL_PORT $MYSQL_DB < $sql_file > /dev/null 2>&1 \
            || true
        shift
    done
}

function usage() {
    echo "sh $0 sql_files"
}

if [ -z "$SQL_FILES" ]; then
    usage
    exit 55
fi

check_conn
if [ $? -ne 0 ]; then
    log "Mysql connect error."
    exit 10
fi

read -r -a s_files <<< "$(tr ',;' ' ' <<< "$SQL_FILES")"
for s_f in ${s_files[@]}; do
    exec_sql_file $s_f
done

log "Used $SECONDS seconds."

